# Generated by Django 4.1 on 2022-09-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bouldering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('user_first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('user_second_name', models.CharField(max_length=30, verbose_name='second name')),
                ('user_email', models.EmailField(max_length=30, verbose_name='email')),
                ('user_password', models.CharField(max_length=30, verbose_name='user password')),
                ('user_about', models.CharField(max_length=500, verbose_name='about me')),
                ('user_profile_pic', models.ImageField(blank=True, null=True, upload_to='static/users/images/', verbose_name='profile picture')),
                ('user_complete_boulders', models.ManyToManyField(related_name='completed_boulders', to='bouldering.boulder', verbose_name='complete boulders')),
                ('user_fa_boulders', models.ManyToManyField(related_name='fa_boulders', to='bouldering.boulder', verbose_name='FA boulders')),
                ('user_favorite_boulders', models.ManyToManyField(related_name='favorite_boulders', to='bouldering.boulder', verbose_name='favorite boulders')),
                ('user_found_boulders', models.ManyToManyField(related_name='found_boulders', to='bouldering.boulder', verbose_name='boulders found')),
            ],
        ),
    ]
