# Generated by Django 4.1 on 2022-11-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouldering', '0005_alter_bouldergrade_boulder_grade_and_more'),
        ('users', '0002_auto_20220901_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_about',
            field=models.CharField(blank=True, max_length=500, verbose_name='about me'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_complete_boulders',
            field=models.ManyToManyField(blank=True, related_name='completed_boulders', to='bouldering.boulder', verbose_name='complete boulders'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_fa_boulders',
            field=models.ManyToManyField(blank=True, related_name='fa_boulders', to='bouldering.boulder', verbose_name='FA boulders'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_favorite_boulders',
            field=models.ManyToManyField(blank=True, related_name='favorite_boulders', to='bouldering.boulder', verbose_name='favorite boulders'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_found_boulders',
            field=models.ManyToManyField(blank=True, related_name='found_boulders', to='bouldering.boulder', verbose_name='boulders found'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_password',
            field=models.CharField(max_length=200, verbose_name='user password'),
        ),
    ]
