# Generated by Django 4.1 on 2022-11-07 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_remove_appuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_first_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_password',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_second_name',
        ),
        migrations.AddField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
