# Generated by Django 4.1 on 2022-09-01 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoulderFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder_name', models.CharField(default=1, max_length=30, verbose_name='finder of the route')),
            ],
        ),
        migrations.CreateModel(
            name='BoulderGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boulder_grade', models.CharField(max_length=10, verbose_name='grade')),
            ],
        ),
        migrations.CreateModel(
            name='BoulderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default=1, max_length=50, verbose_name='location name')),
                ('location_info', models.CharField(default='everything is obvious', max_length=400, verbose_name='additional information about boulder')),
            ],
        ),
        migrations.CreateModel(
            name='BoulderSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_grade', models.CharField(default=1, max_length=50, verbose_name='safety grade')),
            ],
        ),
        migrations.CreateModel(
            name='BoulderSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(default=1, max_length=50, verbose_name='sector name')),
                ('sector_coords', models.CharField(blank=True, default=1, max_length=200, null=True, verbose_name='sector coordinates from google maps')),
                ('sector_location', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='bouldering.boulderlocation', verbose_name='sector location')),
            ],
        ),
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boulder_name', models.CharField(max_length=50, verbose_name='boulder name')),
                ('boulder_photo', models.ImageField(blank=True, null=True, upload_to='static/boulders/images/', verbose_name='Фото')),
                ('boulder_coords', models.URLField(blank=True, help_text='Принимаются метки с гугл карт', max_length=1000, null=True, verbose_name='Ссылка на локацию трассы')),
                ('boulder_info', models.CharField(blank=True, default='no information', max_length=300, null=True, verbose_name='information about a boulder')),
                ('boulder_finder', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='bouldering.boulderfinder', verbose_name='boulder finder')),
                ('boulder_grade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bouldering.bouldergrade', verbose_name='boulder grade')),
                ('boulder_location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bouldering.boulderlocation', verbose_name='boulder location')),
                ('boulder_safety', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bouldering.bouldersafety', verbose_name='boulder safety level')),
                ('boulder_sector', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='bouldering.bouldersector', verbose_name='sector where boulder is located')),
            ],
        ),
    ]
