# Generated by Django 4.1 on 2022-09-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouldering', '0001_initial'),
    ]

    operations = [
    ]
