# Generated by Django 4.1.7 on 2023-02-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouldering', '0006_alter_boulder_boulder_finder_delete_boulderfinder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boulder',
            options={'verbose_name': 'Boulder', 'verbose_name_plural': 'Boulders'},
        ),
        migrations.AlterModelOptions(
            name='bouldergrade',
            options={'verbose_name': 'Boulder grade', 'verbose_name_plural': 'Boulder grades'},
        ),
        migrations.AlterModelOptions(
            name='boulderlocation',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='bouldersafety',
            options={'verbose_name': 'Safety grade', 'verbose_name_plural': 'Safety grades'},
        ),
        migrations.AlterModelOptions(
            name='bouldersector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
    ]
