# Generated by Django 4.1.7 on 2023-06-22 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bouldering', '0007_alter_boulder_options_alter_bouldergrade_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boulder',
            name='boulder_photo',
        ),
        migrations.CreateModel(
            name='BoulderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boulder_photo', models.ImageField(blank=True, null=True, upload_to='static/boulders/images/', verbose_name='Фото')),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouldering.boulder')),
            ],
            options={
                'verbose_name': 'Boulder Photo',
                'verbose_name_plural': 'Boulder Photos',
            },
        ),
    ]
