# Generated by Django 4.1.7 on 2023-06-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouldering', '0008_remove_boulder_boulder_photo_boulderphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boulderphoto',
            name='boulder',
        ),
        migrations.AddField(
            model_name='boulder',
            name='boulder_photos',
            field=models.ManyToManyField(to='bouldering.boulderphoto'),
        ),
    ]
