# Generated by Django 4.1.7 on 2023-10-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouldering', '0009_remove_boulderphoto_boulder_boulder_boulder_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boulderphoto',
            old_name='boulder_photo',
            new_name='photo',
        ),
    ]
